name: Send Slack Message

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1-5'  # 매주 월~금, 한국 시간 오전 10시(테스트용. 오후시간으로 변경예정)

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install slack_sdk gspread oauth2client

      - name: Save credentials.json from base64
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_B64 }}" | base64 -d > credentials.json

      - name: Run Slack bot
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python daily_slack_bot-googlesheets.py
